name: Publish to Comfy registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

<<<<<<< HEAD
=======
permissions:
  issues: write

>>>>>>> upstream/main
jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======
    if: ${{ github.repository_owner == 'Kosinkadink' }}
>>>>>>> upstream/main
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Publish Custom Node
<<<<<<< HEAD
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }} ## Add your own personal access token to your Github Repository secrets and reference it here.
=======
        uses: Comfy-Org/publish-node-action@v1
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }} ## Add your own personal access token to your Github Repository secrets and reference it here.
>>>>>>> upstream/main
